package az.training.test.exception;

public class PersonNotFoundException extends RuntimeException{
}
